// LOADER
export const START_LOADING="START_LOADING";
export const END_LOADNG="END_LOADING";

//AUTH
export const LOGIN="LOGIN";
export const LOGOUT="LOGOUT";



//MODAL
export const MAINMSGUPDATE='MAINMSGUPDATE';
export const SECMSGUPDATE='SECMSGUPDATE';
export const MODALSTATEUPDATE='MODALSTATEUPDATE';
export const NEWCHATMODALSTATE='NEWCHATMODALSTATE';
export const NEWCHATNAME='NEWCHATNAME';
export const NEWCHATMEMBER='NEWCHATMEMBER';